site_name: pydkit
repo_url: https://github.com/manimozaffar/pydkit
site_url: https://manimozaffar.github.io/pydkit
site_description: Extended kit and tools for pydantic, to enjoy pydantic even more!
site_author: Mani Mozaffar
edit_uri: edit/main/docs/
repo_name: manimozaffar/pydkit
copyright: Maintained by <a href="https://manimozaffar.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/manimozaffar/pydkit
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pydkit

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
